/// <summary>
/// Represents a record of a sorting operation's history.
/// </summary>
public class SortingHistory
{
    public int Id { get; set; }
    public string Algorithm { get; set; }
    public string Input { get; set; }
    public string Output { get; set; }
    public DateTime SortDate { get; set; }


    /// <summary>
    /// Initializes a new instance of the <see cref="SortingHistory"/> class with the specified values.
    /// </summary>
    /// <param name="algorithm">The name of the sorting algorithm used.</param>
    /// <param name="input">The input data provided for the sorting operation.</param>
    /// <param name="output">The sorted output data generated by the sorting operation.</param>
    /// <param name="sortDate">The date and time when the sorting operation was performed.</param>
    public SortingHistory(string algorithm, string input, string output, DateTime sortDate)
    {
        Algorithm = algorithm;
        Input = input;
        Output = output;
        SortDate = sortDate;
    }
}